{#if user != null}
  <Dialog
    use={usePass}
    bind:open
    aria-labelledby="tilmeld-two-factor-title"
    aria-describedby="tilmeld-two-factor-content"
    surface$class="tilmeld-two-factor-dialog-surface"
    {...exclude($$restProps, [
      'password$',
      'code$',
      'closeButton$',
      'setupButton$',
      'removeButton$',
      'progress$',
    ])}
  >
    <!-- Title cannot contain leading whitespace due to mdc-typography-baseline-top() -->
    <Title id="tilmeld-two-factor-title">{title}</Title>
    {#if hasTOTPSecret === false}
      <Content id="tilmeld-two-factor-content">
        {#if totpSecret == null}
          <p>
            2 Factor Authentication (2FA) adds an additional layer of security.
            With 2FA, no one can log in without your authenticator device, even
            with your password.
          </p>

          <p>
            You'll need an authenticator app that supports TOTP codes. Some
            popular apps are linked here.
          </p>

          <h6 style="margin-top: 0;">Twilio Authy</h6>

          <ul>
            <li>
              <a
                href="https://play.google.com/store/apps/details?id=com.authy.authy"
                target="_blank"
                rel="noopener noreferrer">Google Play Store</a
              >
            </li>
            <li>
              <a
                href="https://apps.apple.com/us/app/twilio-authy/id494168017"
                target="_blank"
                rel="noopener noreferrer">Apple App Store</a
              >
            </li>
            <li>
              <a
                href="https://authy.com/download/"
                target="_blank"
                rel="noopener noreferrer">Desktop App</a
              >
            </li>
          </ul>

          <h6 style="margin-top: 0;">Google Authenticator</h6>

          <ul>
            <li>
              <a
                href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2"
                target="_blank"
                rel="noopener noreferrer">Google Play Store</a
              >
            </li>
            <li>
              <a
                href="https://apps.apple.com/us/app/google-authenticator/id388497605"
                target="_blank"
                rel="noopener noreferrer">Apple App Store</a
              >
            </li>
          </ul>

          <h6 style="margin-top: 0;">Microsoft Authenticator</h6>

          <ul>
            <li>
              <a
                href="https://play.google.com/store/apps/details?id=com.azure.authenticator"
                target="_blank"
                rel="noopener noreferrer">Google Play Store</a
              >
            </li>
            <li>
              <a
                href="https://apps.apple.com/us/app/microsoft-authenticator/id983156458"
                target="_blank"
                rel="noopener noreferrer">Apple App Store</a
              >
            </li>
          </ul>

          <p>
            Once your authenticator app is ready, continue to generate a QR
            code.
          </p>
        {:else}
          <p>Scan this QR code with your authenticator app:</p>

          <div style="text-align: center;">
            <img alt="TOTP Set Up QR Code" src={totpSecret.qrcode} />
          </div>

          <p>Or you can enter this code manually into your app:</p>

          <div style="text-align: center;">
            <code style="word-break: break-all;">{totpSecret.secret}</code>
          </div>

          <p>Enter your password to allow this account change:</p>

          <div>
            <Textfield
              bind:value={password}
              label="Password"
              type="password"
              style="width: 100%;"
              input$autocomplete="current-password"
              {...prefixFilter($$restProps, 'password$')}
            />
          </div>

          <p>
            Enter a code generated by your app to confirm the account is
            configured correctly:
          </p>

          <div>
            <Textfield
              bind:value={code}
              label="2FA Code"
              style="width: 100%;"
              input$maxlength={6}
              input$minlength={6}
              {...prefixFilter($$restProps, 'code$')}
            />
          </div>
        {/if}

        {#if failureMessage}
          <div class="tilmeld-two-factor-failure">
            {failureMessage}
          </div>
        {/if}

        {#if loading}
          <div class="tilmeld-two-factor-loading">
            <CircularProgress
              style="height: 24px; width: 24px;"
              indeterminate
              {...prefixFilter($$restProps, 'progress$')}
            />
          </div>
        {/if}
      </Content>
      <Actions>
        <Button
          disabled={loading}
          {...prefixFilter($$restProps, 'closeButton$')}
        >
          <Label>Close</Label>
        </Button>
        {#if totpSecret == null}
          <Button
            on:click$preventDefault$stopPropagation={beginSetup}
            disabled={loading}
            {...prefixFilter($$restProps, 'setupButton$')}
          >
            <Label>Set Up 2FA</Label>
          </Button>
        {:else}
          <Button
            on:click$preventDefault$stopPropagation={enableTOTP}
            disabled={loading}
            {...prefixFilter($$restProps, 'setupButton$')}
          >
            <Label>Enable 2FA</Label>
          </Button>
        {/if}
      </Actions>
    {:else if hasTOTPSecret === true}
      <Content id="tilmeld-two-factor-content">
        <p>
          2 Factor Authentication (2FA) is enabled on your account. If you'd
          like to disable it, you can provide your password and a code generated
          by your Authenticator app. You can re-enable it by generating a new QR
          code at any time.
        </p>

        <div>
          <Textfield
            bind:value={password}
            label="Password"
            type="password"
            style="width: 100%;"
            input$autocomplete="current-password"
            {...prefixFilter($$restProps, 'password$')}
          />
        </div>

        <div>
          <Textfield
            bind:value={code}
            label="2FA Code"
            style="width: 100%;"
            input$maxlength={6}
            input$minlength={6}
            {...prefixFilter($$restProps, 'code$')}
          />
        </div>

        <slot name="additional" />

        {#if failureMessage}
          <div class="tilmeld-two-factor-failure">
            {failureMessage}
          </div>
        {/if}

        {#if loading}
          <div class="tilmeld-two-factor-loading">
            <CircularProgress
              style="height: 24px; width: 24px;"
              indeterminate
              {...prefixFilter($$restProps, 'progress$')}
            />
          </div>
        {/if}
      </Content>
      <Actions>
        <Button
          disabled={loading}
          {...prefixFilter($$restProps, 'closeButton$')}
        >
          <Label>Close</Label>
        </Button>
        <Button
          on:click$preventDefault$stopPropagation={disableTOTP}
          disabled={loading}
          {...prefixFilter($$restProps, 'removeButton$')}
        >
          <Label>Disable 2FA</Label>
        </Button>
      </Actions>
    {:else}
      <div class="tilmeld-two-factor-loading">
        <CircularProgress
          style="height: 24px; width: 24px;"
          indeterminate
          {...prefixFilter($$restProps, 'progress$')}
        />
      </div>
    {/if}
  </Dialog>
{/if}

<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { get_current_component } from 'svelte/internal';
  import CircularProgress from '@smui/circular-progress';
  import Dialog, { Title, Content, Actions } from '@smui/dialog';
  import Textfield from '@smui/textfield';
  import Button, { Label } from '@smui/button';
  import type { ActionArray } from '@smui/common/internal';
  import {
    forwardEventsBuilder,
    exclude,
    prefixFilter,
  } from '@smui/common/internal';
  import type { CurrentUserData } from '@nymphjs/tilmeld-client';
  import type { User as UserClass } from '@nymphjs/tilmeld-client';

  const forwardEvents = forwardEventsBuilder(get_current_component());

  export let use: ActionArray = [];
  $: usePass = [forwardEvents, ...use] as ActionArray;
  export let open = false;
  export let title = 'Manage Two Factor Authentication';
  export let User: typeof UserClass;
  export let user: (UserClass & CurrentUserData) | undefined = undefined;

  let loading = false;
  let failureMessage: string | undefined = undefined;

  /** Server provided. You can bind to it if you need to. */
  export let hasTOTPSecret: boolean | null = null;
  /** Server provided. You can bind to it if you need to. */
  export let totpSecret: {
    uri: string;
    qrcode: string;
    secret: string;
  } | null = null;
  /** User provided. You can bind to it if you need to. */
  export let password = '';
  /** User provided. You can bind to it if you need to. */
  export let code = '';

  $: if (!open) {
    loading = false;
    failureMessage = undefined;
    totpSecret = null;
    password = '';
    code = '';
  }

  const onLogin = (currentUser: UserClass & CurrentUserData) => {
    user = currentUser;
    hasTOTPSecret = null;
    user.$hasTOTPSecret().then(
      (value) => {
        hasTOTPSecret = value;
        failureMessage = undefined;
      },
      (e) => {
        hasTOTPSecret = null;
        failureMessage = e?.message;
      }
    );
  };
  const onLogout = () => {
    user = undefined;
    hasTOTPSecret = null;
  };

  onMount(async () => {
    User.on('login', onLogin);
    User.on('logout', onLogout);
    if (user === undefined) {
      user = (await User.current()) ?? undefined;
    }
    if (user) {
      try {
        hasTOTPSecret = await user.$hasTOTPSecret();
        failureMessage = undefined;
      } catch (e: any) {
        hasTOTPSecret = null;
        failureMessage = e?.message;
      }
    } else {
      hasTOTPSecret = null;
    }
  });

  onDestroy(() => {
    User.off('login', onLogin);
    User.off('logout', onLogout);
  });

  async function beginSetup() {
    loading = true;

    if (user == null) {
      failureMessage = 'You must be logged in.';
      loading = false;
      return;
    }

    try {
      totpSecret = await user.$getNewTOTPSecret();
    } catch (e: any) {
      failureMessage = e?.message;
    }
    loading = false;
  }

  async function enableTOTP() {
    if (password === '') {
      failureMessage = 'You need to enter your current password';
      return;
    }

    if (code === '') {
      failureMessage = 'You need to enter a generated code';
      return;
    }

    if (totpSecret == null) {
      failureMessage = 'TOTP secret is not set';
      return;
    }

    failureMessage = undefined;
    loading = true;

    // Get the current user again, in case their data has changed.
    user = (await User.current()) ?? undefined;

    if (user == null) {
      failureMessage = 'You must be logged in.';
      loading = false;
      return;
    }

    try {
      // Save the user's TOTP secret.
      const data = await user.$saveTOTPSecret({
        password,
        secret: totpSecret.secret,
        code,
      });

      if (!data.result) {
        failureMessage = data.message;
      } else {
        open = false;
        hasTOTPSecret = true;
      }
    } catch (e: any) {
      failureMessage = e?.message;
    }
    loading = false;
  }

  async function disableTOTP() {
    if (password === '') {
      failureMessage = 'You need to enter your current password';
      return;
    }

    if (code === '') {
      failureMessage = 'You need to enter a generated code';
      return;
    }

    failureMessage = undefined;
    loading = true;

    // Get the current user again, in case their data has changed.
    user = (await User.current()) ?? undefined;

    if (user == null) {
      failureMessage = 'You must be logged in.';
      loading = false;
      return;
    }

    try {
      // Remove the user's TOTP secret.
      const data = await user.$removeTOTPSecret({
        password,
        code,
      });

      if (!data.result) {
        failureMessage = data.message;
      } else {
        open = false;
        hasTOTPSecret = false;
      }
    } catch (e: any) {
      failureMessage = e?.message;
    }
    loading = false;
  }
</script>

<style>
  :global(.mdc-dialog .mdc-dialog__surface.tilmeld-two-factor-dialog-surface) {
    width: 400px;
    max-width: calc(100vw - 32px);
  }
  .tilmeld-two-factor-failure {
    margin-top: 1em;
    color: var(--mdc-theme-error, #f00);
  }
  .tilmeld-two-factor-loading {
    display: flex;
    justify-content: center;
    align-items: center;
  }
</style>
